import re

# Map (dict) that maps popular script file extensions to their associated language
fileExtensionMap = {
    "py": "Python",
    "js": "JavaScript",
    "java": "Java",
    "cpp": "C++",
    "c": "C",
    "go": "Golang",
    "html": "HTML",
    "css": "CSS",
    "php": "PHP",
    "sh": "Bash",
    "sc": "Scala",
    "scala": "Scala",
    "md": "Markdown"
}

# Function to extract the file extension from a file's path
def getFileExtension(path):
    """
    Determine the file extension from the given file path.

    Args:
    - path (str): The path of the file.

    Returns:
    - str or None: The file extension if found, otherwise None.
    """
    # Regular expression pattern to match file extension
    pattern = r'\.(?!\.)[a-zA-Z0-9+]+$'

    # Use regex expression to get file extension
    match = re.search(pattern, path)

    if match:
        # Remove leading period
        return match.group(0)[1:]
    else:
        return None

# Function to determine the programming language based on the file extension
def getScriptLanguage(path):
    """
    Determine the programming language based on the file extension.

    Args:
    - file_extension (str): The file extension of the script file.

    Returns:
    - str: The programming language corresponding to the file extension.
    """
    extension = getFileExtension(path)
    language = fileExtensionMap.get(extension.lower(), "Unknown")

    return language

# Write model's output string to a markdown file
def writeOutputToMarkdownFile(fileName, modelOutputString, title):
    """
    Write the model output to a markdown file.

    Args:
    - fileName (str): The name of the markdown file.
    - modelOutputString (str): The output string generated by the model.
    - title (str): The title of the markdown file.
    """
    # Join the formatted outputs into a single string
    markdownTitle = f"# {title}\n\n" + "\n\n---\n\n"

    # Write the content to the file
    with open(f'{fileName}.md', 'w') as file:
        file.write(markdownTitle)
        file.write(modelOutputString)